### ISSUE TITLE
Redis server down due to disc usage

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/infrastructure-env-staging#23]
On 19th May 2022 between 10 am and 2 pm redis server stopped to work, [what led to API out of service](https://github.com/serlo/api.serlo.org/issues/74). 
The cause was too much disc usage : the `/data` mount was at 100% (8Gi). 
After removing the heavy apendonly.aof file, it worked again.

TODO
- [ ] Redo all manual changes:
- [x] reset storage increase of pv, pvc and pod
- [ ] Put a limit for apendonly.aof
- [ ] Investigate the cause of so much disc comsumption (at prod it was at 328Mi)
- [ ] Create recovery workflows for such cases

**Comment by hugotiburtino** [comment]
We couldn't find any hint yet, almost 6 months after the disturb. But it seems the problem persists:
At 01 nov,
In prod:
`/dev/sdb        7.8G  378M  7.4G   5% /data`
In staging:
`/dev/sdb        7.8G  1.8G  6.0G  24% /data`

**Comment by hugotiburtino** [comment]
Indeed, the delayed jobs of the SWR Queue in staging is the reason for so much storage usage.
From the swq dashboard of staging:
![image](https://user-images.githubusercontent.com/45924645/202039038-109f5701-5b34-454f-b30e-fa7219ad2b5a.png)

```console
# STAGING
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        7.8G  2.1G  5.7G  27% /data
```
```console
# PROD
k -n api exec -it redis-master-0 -- df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        7.8G  491M  7.3G   7% /data
```
If we sum the used system memory of the SWR Worker from staging (1.74 GB) with the storage that it was indeed supposed to have like in prod (491MG) we get +- 2.1 GB.

@inyono @kulla any idea why the SWR Queue isn't working in staging?

**Comment by kulla** [comment]
Maybe there is no SWR queue worker on staging?!

**Comment by hugotiburtino** [comment]
Closing since we will find another way of managing redis
